# Generated by Django 5.2.8 on 2025-11-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('DIÁRIA', 'Diária'), ('PASSEIO', 'Passeio'), ('CASA', 'Casa')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
