# Generated by Django 5.2.8 on 2025-11-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_fotografia_categoria_alter_fotografia_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('DIÁRIA', 'Diária'), ('PASSEIO', 'Passeio'), ('CASA', 'Casa'), ('OUTROS', 'Outros')], default='', max_length=100),
        ),
    ]
